#!/bin/bash

sudo add-apt-repository ppa:neovim-ppa/unstable

sudo apt-get update

sudo apt-get install neovim

sudo apt-get install ripgerp

sudo apt install xclip

cd ~/.config

git clone git@github.com:aragami3070/nvim.git
